# Generated by Django 5.0.6 on 2025-02-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=2)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('valor_planejado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_arrecadado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_pessoas', models.IntegerField(blank=True, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tipoevento')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
