# Generated by Django 5.0.6 on 2025-02-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_planejamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jack_jill', models.BooleanField(blank=True, default=False, null=True, verbose_name='Jack & Jill')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.categoria')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
