# Generated by Django 5.0.6 on 2025-02-18 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_evento_contador_barco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='contador_barco',
            field=models.IntegerField(default=0, editable=False, verbose_name='Vagas preenchidas '),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('ano', models.IntegerField()),
                ('cep', models.CharField(blank=True, help_text='Digite um CEP válido para atualizar os campos abaixo.', max_length=9, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lote')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
