# Generated by Django 5.0.6 on 2025-02-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_entradas_saidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto a ser aplicado no valor do lote', max_digits=10),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='parcelas',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Número de parcelas para pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total após aplicar desconto e incluir eventos', max_digits=10, null=True),
        ),
    ]
