# Generated by Django 5.0.6 on 2025-02-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_inscricao_desconto_inscricao_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário do evento', max_digits=10, null=True),
        ),
    ]
