# Generated by Django 5.0.6 on 2025-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_evento_valor_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricaoevento',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='contador_barco',
        ),
        migrations.AddField(
            model_name='evento',
            name='contador_inscricoes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Inscrições'),
        ),
    ]
