# Generated by Django 5.0.6 on 2025-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_proximo_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
